default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: yaro
  password: pass
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: doesmystartupideasuck_development

test:
  <<: *default
  database: doesmystartupideasuck_test

production:
  <<: *default
  database: doesmystartupideasuck_production